<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INPAVANKUMAR01" failures="3" tests="13" name="Test1" time="0.132" errors="0" timestamp="15 Mar 2025 10:39:29 GMT">
  <testcase classname="com.digicert.qa.testcert.CertificateStructureValidationTest" name="testValidateCertExpirydate" time="0.028"/>
  <testcase classname="com.digicert.qa.testcert.CertificateStructureValidationTest" name="testValidateCertSignatureAlgorith" time="0.005"/>
  <testcase classname="com.digicert.qa.testcert.CertificateStructureValidationTest" name="testValidateCertVersion" time="0.005"/>
  <testcase classname="com.digicert.qa.testcert.CertificateStructureValidationTest" name="testValidateCertificate" time="0.004"/>
  <testcase classname="com.digicert.qa.testcert.CertificateStructureValidationTest" name="testValidateCommanName" time="0.004"/>
  <testcase classname="com.digicert.qa.testcert.CertificateStructureValidationTest" name="testValidateIssuer" time="0.006"/>
  <testcase classname="com.digicert.qa.testcert.CertificateDataDrivenTest" name="testCertificateExpiration" time="0.005"/>
  <testcase classname="com.digicert.qa.testcert.CertificateDataDrivenTest" name="testCertificateExpiration" time="0.002"/>
  <testcase classname="com.digicert.qa.testcert.CertificateDataDrivenTest" name="testCertificateExpiration" time="0.002"/>
  <testcase classname="com.digicert.qa.testcert.CertificateNegativeTests" name="testCertificateExpiry" time="0.004"/>
  <testcase classname="com.digicert.qa.testcert.CertificateNegativeTests" name="testCertificateExpiry_WithSpecificDate" time="0.005">
    <failure type="java.lang.AssertionError" message="The certificate is not valid by this date- Thu Mar 12 10:31:30 IST 2026 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The certificate is not valid by this date- Thu Mar 12 10:31:30 IST 2026 expected [true] but found [false]
	at com.digicert.qa.testcert.CertificateNegativeTests.testCertificateExpiry_WithSpecificDate(CertificateNegativeTests.java:49)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCertificateExpiry_WithSpecificDate -->
  <testcase classname="com.digicert.qa.testcert.CertificateNegativeTests" name="testMalformedCertificate" time="0.004">
    <failure type="java.lang.AssertionError" message="==The certificate at &amp;apos;&amp;quot; + malformedcertificatePath + &amp;quot;&amp;apos; is malformed certificate== expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ==The certificate at '" + malformedcertificatePath + "' is malformed certificate== expected [true] but found [false]
	at com.digicert.qa.testcert.CertificateNegativeTests.testMalformedCertificate(CertificateNegativeTests.java:57)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testMalformedCertificate -->
  <testcase classname="com.digicert.qa.testcert.CertificateNegativeTests" name="testWeakCertificateKeySize" time="0.003">
    <failure type="java.lang.AssertionError" message="==The certificate at &amp;apos;&amp;quot; + malformedcertificatePath + &amp;quot;&amp;apos; is malformed certificate== expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ==The certificate at '" + malformedcertificatePath + "' is malformed certificate== expected [true] but found [false]
	at com.digicert.qa.testcert.CertificateNegativeTests.testWeakCertificateKeySize(CertificateNegativeTests.java:73)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testWeakCertificateKeySize -->
</testsuite> <!-- Test1 -->
